export const ADD_ORDER_SUCCESS= "ADD_ORDE_SUCCESS"
export const ADD_ORDER_FAILED = "ADD_ORDER_FAILED"

export const GET_ORDER = "GET_ORDER"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILED = "GET_ORDER_FAILED"

export const DELETE_ORDER = "DELETE_ORDER"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILED = "DELETE_ORDER_FAILED"

export const DELETE_ALL_ORDER = "DELETE_ALL_ORDER"
export const DELETE_ALL_ORDER_SUCCESS = "DELETE_ALL_ORDER_SUCCESS"
export const DELETE_ALL_ORDER_FAILED = "DELETE_ALL_ORDER_FAILED"
