export const GET_PARTNER = "GET_PARTNER"
export const GET_PARTNER_SUCCESS = "GET_PARTNER_SUCCESS"
export const GET_PARTNER_FAILED = "GET_PARTNER_FAILED"

export const GET_PARTNER_PRODUCT = "GET_PARTNER_PRODUCT"
export const GET_PARTNER_PRODUCT_SUCCESS = "GET_PARTNER_PRODUCT_SUCCESS"
export const GET_PARTNER_PRODUCT_FAILED = "GET_PARTNER_PRODUCT_FAILED"