export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED"

export const GET_PRODUCT_SELLER = "GET_PRODUCT_SELLER"
export const GET_PRODUCT_SELLER_SUCCESS = "GET_PRODUCT_SELLER_SUCCESS"
export const GET_PRODUCT_SELLER_FAILED = "GET_PRODUCT_SELLER_FAILED"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED"